---
apiVersion: v1
kind: Pod
metadata: 
  name: mysql
  namespace: default
  labels:
    name: mysql
spec:
  containers:
  - name: mysql
    image: mysql:latest
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: Pa$$word1
    ports: 
    - name: mysql
      containerPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    name: mysql
spec:
  ports:
  - port: 3306
  selector:
    name: mysql
  type: ClusterIP